<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization><!-- Culture de-DE en-GB gehen bei true nicht! -->
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <GenerateDocumentationFile>true</GenerateDocumentationFile><!-- Generate a xml file containing API documentation. -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\csbp\CSBP.Services\CSBP.Services.csproj" />
    <ProjectReference Include="..\BlazorBp.Core\BlazorBp.Core.csproj" />
    <ProjectReference Include="..\BlazorBp.Forms.Demo\BlazorBp.Forms.Demo.csproj" />
  </ItemGroup>

  <ItemGroup> <!-- Empfehlung von GPT-6: Wildcard-Version sind aus Security-Gründen nicht optimal. -->
    <PackageReference Include="NeoSmart.Caching.Sqlite.AspNetCore" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
  </ItemGroup>
</Project>
